/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpmbRouteImport } from './routes/spmb'
import { Route as ProgramKeahlianTkjRouteImport } from './routes/program-keahlian-tkj'
import { Route as ProgramKeahlianRouteImport } from './routes/program-keahlian'
import { Route as PklRouteImport } from './routes/pkl'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SpmbRoute = SpmbRouteImport.update({
  id: '/spmb',
  path: '/spmb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKeahlianTkjRoute = ProgramKeahlianTkjRouteImport.update({
  id: '/program-keahlian-tkj',
  path: '/program-keahlian-tkj',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKeahlianRoute = ProgramKeahlianRouteImport.update({
  id: '/program-keahlian',
  path: '/program-keahlian',
  getParentRoute: () => rootRouteImport,
} as any)
const PklRoute = PklRouteImport.update({
  id: '/pkl',
  path: '/pkl',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/informasi': typeof InformasiRoute
  '/kontak': typeof KontakRoute
  '/pkl': typeof PklRoute
  '/program-keahlian': typeof ProgramKeahlianRoute
  '/program-keahlian-tkj': typeof ProgramKeahlianTkjRoute
  '/spmb': typeof SpmbRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/informasi': typeof InformasiRoute
  '/kontak': typeof KontakRoute
  '/pkl': typeof PklRoute
  '/program-keahlian': typeof ProgramKeahlianRoute
  '/program-keahlian-tkj': typeof ProgramKeahlianTkjRoute
  '/spmb': typeof SpmbRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/informasi': typeof InformasiRoute
  '/kontak': typeof KontakRoute
  '/pkl': typeof PklRoute
  '/program-keahlian': typeof ProgramKeahlianRoute
  '/program-keahlian-tkj': typeof ProgramKeahlianTkjRoute
  '/spmb': typeof SpmbRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/informasi'
    | '/kontak'
    | '/pkl'
    | '/program-keahlian'
    | '/program-keahlian-tkj'
    | '/spmb'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/informasi'
    | '/kontak'
    | '/pkl'
    | '/program-keahlian'
    | '/program-keahlian-tkj'
    | '/spmb'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/informasi'
    | '/kontak'
    | '/pkl'
    | '/program-keahlian'
    | '/program-keahlian-tkj'
    | '/spmb'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  InformasiRoute: typeof InformasiRoute
  KontakRoute: typeof KontakRoute
  PklRoute: typeof PklRoute
  ProgramKeahlianRoute: typeof ProgramKeahlianRoute
  ProgramKeahlianTkjRoute: typeof ProgramKeahlianTkjRoute
  SpmbRoute: typeof SpmbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spmb': {
      id: '/spmb'
      path: '/spmb'
      fullPath: '/spmb'
      preLoaderRoute: typeof SpmbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-keahlian-tkj': {
      id: '/program-keahlian-tkj'
      path: '/program-keahlian-tkj'
      fullPath: '/program-keahlian-tkj'
      preLoaderRoute: typeof ProgramKeahlianTkjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-keahlian': {
      id: '/program-keahlian'
      path: '/program-keahlian'
      fullPath: '/program-keahlian'
      preLoaderRoute: typeof ProgramKeahlianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkl': {
      id: '/pkl'
      path: '/pkl'
      fullPath: '/pkl'
      preLoaderRoute: typeof PklRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  InformasiRoute: InformasiRoute,
  KontakRoute: KontakRoute,
  PklRoute: PklRoute,
  ProgramKeahlianRoute: ProgramKeahlianRoute,
  ProgramKeahlianTkjRoute: ProgramKeahlianTkjRoute,
  SpmbRoute: SpmbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
